#---
#include:
#  - board: nrfmicro_13_52833
#    shield: corne_left
#  - board: nrfmicro_13_52833
#    shield: corne_right

---
include:
  - board: nice_nano
    shield: corne_left
    snippet: zmk-usb-logging
#  - board: nice_nano
#    shield: corne_right
#  - board: nice_nano
#    shield: settings_reset
